name: CI
on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  job-develop:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install dep
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm test -- --coverage
        env:
         CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain elegant-fairies.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN}}

